name: sshicstuff
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - bowtie2=2.5.1
  - cooler=0.10.2
  - minimap2
  - pairtools=1.1.0
  - pip>=24.3.1
  - pysam=0.22.0
  - python<3.11
  - samtools
  - seqtk

