name: sshicstuff
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - biopython=1.84
  - bowtie2
  - cooler
  - docopt=0.6.2
  - minimap2
  - matplotlib>=3.6.0
  - numpy>=1.26.0
  - pandas>=2.2.2
  - pairtools=1.1.0
  - pip>=23.3.1
  - plotly>=5.5.0
  - pyfastx
  - pysam=0.22.0
  - python<3.11
  - samtools
  - scipy>=1.10.0
  - seqtk
  - dash>=2.16.1
  - dash-bootstrap-components=1.6.0
  - dash-daq
  - flask=3.0.3
  - pytest>=8.1.0
  - setuptools=72.1.0
  - pip :
      - git+https://github.com/koszullab/hicstuff.git
