name: sshicstuff
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - biopython=1.83
  - bowtie2
  - cooler
  - docopt
  - hicstuff>=3.2.2
  - minimap2
  - matplotlib>=3.6.0
  - numpy>=1.23.0
  - pandas>=2.0.0
  - pairtools=1.0.2
  - pip>=23.0.0
  - plotly>=5.5.0
  - pyfastx
  - pysam
  - python=3.10.14
  - samtools
  - scipy>=1.10.0
  - seqtk
