name: sshicstuff_env
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - bowtie2
  - cooler
  - minimap2
  - pairtools=1.1.0
  - pip>=24.3.1
  - pysam=0.22.1
  - python=3.12
  - python-build=1.2.2.post1
  - samtools
  - seqtk

