name: sshicstuff
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - pip=23.0.0
  - pip:
      - -r file:requirements.txt
  - biopython=1.83
  - bowtie2
  - bwa
  - cooler
  - htslib
  - minimap2
  - samtools
  - -seqtk
